### PR TITLE
Lettrythis

### PR DESCRIPTION
**Pull request by Drybones3363**

### CODE REVIEW

**Comment by TheNexusAvenger** [comment]
I won't be accepting modifications like this...

**Comment by Drybones3363** [comment]
wait is this nexus avenger?

**Comment by Drybones3363** [comment]
oh whoops sorry
i didn’t mean to do what i did, i thought a pull request did something else… lol my bad

**Comment by TheNexusAvenger** [comment]
It's ok. The correct button is right under your avatar in the top right corner with the word "Fork".

**Comment by Drybones3363** [comment]
yeah, i forked and everything and tried adding new songs, but gh-pages wasn’t updating, so i did pull request cause that sounded good lol
again sorry about that

**Pull request closed without merging**
